global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'go-agent-rpi'
    static_configs:
      - targets: ['192.168.0.110:9090']
