global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # scrape Prometheus itself
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]

  # scrape edge-agent on your Pi
  - job_name: edge-agent
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ["192.168.0.110:9090"]

  # scrape Alertmanager
  - job_name: alertmanager
    static_configs:
      - targets: ["alertmanager:9093"]

  # ← new job for your control‑plane API over HTTPS
  - job_name: control-plane-api
    scheme: https
    metrics_path: /metrics
    tls_config:
      insecure_skip_verify: true      # skip cert validation (self‑signed)
    static_configs:
      - targets: ["api:8443"]         # “api” is your compose service hostname
