global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is 1 minute.

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            # Alertmanager's default port is 9093. Service name is 'alertmanager' in compose.
            - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
# NOTE: Your compose command also uses --rule.file. This section ensures rules are loaded
# even if the command flag changes and allows for globbing if you add more rule files later.
rule_files:
  - "/etc/prometheus/rules/*.yml" # Path inside the container where rules files are mounted

# A list of scrape configurations.
scrape_configs:
  # Job to scrape Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"] # Prometheus's own metrics endpoint

  # Job to scrape the edge-agent running on the Raspberry Pi
  - job_name: "edge-agent"
    metrics_path: /metrics # Path specified in your Go agent code
    scheme: http           # Your agent uses HTTP for metrics
    static_configs:
      - targets: ["192.168.0.110:9090"] # <-- Your Raspberry Pi's IP address and agent's metrics port

  # Job to scrape Alertmanager
  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"] # Alertmanager service name and port
