"""Change schedule column to string

Revision ID: 29103806f22a
Revises: 2c0dbacc6304
Create Date: 2025-05-03 22:33:21.475144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29103806f22a'
down_revision: Union[str, None] = '2c0dbacc6304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('jobs', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('jobs', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_jobs_device_state', table_name='jobs')
    op.create_index(op.f('ix_jobs_state'), 'jobs', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jobs_state'), table_name='jobs')
    op.create_index('ix_jobs_device_state', 'jobs', ['device_id', 'state'], unique=False)
    op.alter_column('jobs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('jobs', 'workflow_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('jobs', 'device_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
