name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PY_VER: "3.12"
  PG_VER: "17"

jobs:
  ###########################
  # 1.  Static checks first #
  ###########################
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Ruff (lint & fmt check)
        run: ruff check .

      - name: MyPy (type checking)
        run: mypy control-plane-api/src tests      # <── adjusted path

  #####################################
  # 2.  Test suite + migrations check #
  #####################################
  tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:${{ env.PG_VER }}
        env:
          POSTGRES_USER: edge
          POSTGRES_PASSWORD: edgepass
          POSTGRES_DB: edgecloud
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U edge -d edgecloud"
          --health-interval=3s
          --health-timeout=2s
          --health-retries=10

    env:
      DATABASE_URL: postgresql+asyncpg://edge:edgepass@localhost:5432/edgecloud

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}

      # ─────────────── install deps ────────────────
      - name: Install project (editable) + dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -e ./control-plane-api"[dev]"   # <── only the real package

      # ─────── run alembic and tests  ──────────────
      - name: Alembic upgrade head
        working-directory: control-plane-api          # <── alembic.ini lives here
        run: alembic upgrade head

      - name: Round-trip latest migration (down & up)
        working-directory: control-plane-api
        run: |
          head_rev=$(alembic current | awk '{print $1}')
          alembic downgrade -1
          alembic upgrade ${head_rev}

      - name: Pytest
        run: pytest -q

