name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  PY_VER: "3.12"          # used later in setup-python

jobs:
  # ──────────────── 1. Lint / type-check ────────────────
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install ruff mypy

      - name: Ruff (lint)
        run: ruff check .

      - name: MyPy (types)
        run: mypy control-plane-api/src

  # ──────────────── 2. Tests + migrations ───────────────
  tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER:     edge
          POSTGRES_PASSWORD: edgepass
          POSTGRES_DB:       edgecloud
        ports:
          - "5432:5432"
        options: >-
          --health-cmd="pg_isready -U edge -d edgecloud"
          --health-interval=3s
          --health-timeout=2s
          --health-retries=10

    env:
      DATABASE_URL: postgresql+asyncpg://edge:edgepass@localhost:5432/edgecloud

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VER }}

      - name: Install control-plane-api + dev tools
        run: |
          python -m pip install --upgrade pip
          pip install -e "./control-plane-api[dev]"

      - name: Run Alembic migrations
        run: |
          cd control-plane-api
          python -m alembic upgrade head

      - name: Migration round-trip (down & up)
        run: |
          cd control-plane-api
          head=$(python -m alembic current | awk '{print $1}')
          python -m alembic downgrade -1
          python -m alembic upgrade "$head"

      - name: Pytest
        run: pytest -q
